version: '3'
volumes:
  express-template-db-data:

services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=express_template_db
    volumes:
      - express-template-db-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    expose:
      - 5432

  server:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    image: express-template:latest
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=express_template_db
      - POSTGRES_SCHEMA=public
    depends_on:
      - postgres
    ports:
      - 3000:3000
